---
title: "Algebra liniowa z geometrią analityczną"
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: Piotr Zamaro zamaro@outlook.com
output: github_document
---


### Opis przedmiotu

Celem przedmiotu **Algebra Liniowa z Geometrią Analityczną** jest wprowadzenie studentów do podstawowych pojęć, twierdzeń i metod algebry liniowej oraz geometrii analitycznej. Przedmiot kładzie nacisk na rozwijanie umiejętności operowania pojęciami takimi jak przestrzenie wektorowe, macierze, wyznaczniki, układy równań liniowych, a także liczby zespolone. Studenci zapoznają się z algebraicznymi strukturami (takimi jak grupy, pierścienie, ciała) oraz ich zastosowaniami w matematyce i informatyce. Dodatkowo w ramach geometrii analitycznej analizowane będą zależności geometryczne w przestrzeniach euklidesowych, w tym wektory, proste, płaszczyzny oraz iloczyny wektorowe i skalarne.

### Treści merytoryczne:

1. **Grupy, pierścienie, ciała:**
   - Podstawowe struktury algebraiczne na przykładzie zbiorów liczb.
   
2. **Liczby zespolone:**
   - Postać algebraiczna i trygonometryczna liczb zespolonych, wzór Moivre’a, pierwiastkowanie liczb zespolonych.
   
3. **Przestrzenie wektorowe:**
   - Pojęcie wektora, podprzestrzeni, kombinacji liniowej, wektory liniowo zależne i niezależne, baza i wymiar przestrzeni.
   
4. **Macierze:**
   - Działania na macierzach, rząd macierzy, metoda eliminacji Gaussa, wyznacznik macierzy kwadratowej, rozwinięcie Laplace'a, macierz odwrotna.
   
5. **Układy równań liniowych:**
   - Twierdzenie Kroneckera-Capellego, wzory Cramera.
   
6. **Przekształcenia liniowe:**
   - Homomorfizmy liniowe, jądro i obraz, przestrzenie izomorficzne, wartości własne i wektory własne.
   
7. **Geometria analityczna:**
   - Iloczyn skalarny, iloczyn wektorowy, obliczanie pól i objętości, proste i płaszczyzny w przestrzeni 3-wymiarowej.

### Cele przedmiotu:
- Ugruntowanie wiedzy na temat podstawowych pojęć i metod algebry liniowej i geometrii analitycznej.
- Rozwijanie umiejętności precyzyjnego operowania pojęciami matematycznymi i ich stosowania w rozwiązywaniu problemów.
- Przygotowanie do wykorzystywania pojęć i narzędzi algebry liniowej w dalszej edukacji oraz w kontekście zagadnień informatycznych i technicznych.

### Efekty uczenia się:

1. **Wiedza:**
   - Student rozumie znaczenie dowodów w matematyce oraz zna podstawowe pojęcia algebry liniowej i geometrii analitycznej.
   
2. **Umiejętności:**
   - Potrafi operować pojęciem przestrzeni wektorowej, macierzy, przekształceń liniowych oraz dostrzegać struktury algebraiczne w różnych zagadnieniach matematycznych.
   
3. **Kompetencje społeczne:**
   - Student jest świadomy ograniczeń swojej wiedzy i rozumie potrzebę dalszego kształcenia oraz potrafi zadawać precyzyjne pytania w celu pogłębiania zrozumienia.

### Metody dydaktyczne:
- **Wykłady:** Prezentacja teoretycznych zagadnień algebry i geometrii z wykorzystaniem multimediów.
- **Ćwiczenia:** Rozwiązywanie zadań opartych na treściach przedstawionych na wykładach, z możliwością dyskusji i wspólnego wyboru najlepszych metod rozwiązania problemów.

### Literatura:

1. **Podstawowa:**
   - Gleichgewicht B., *Algebra*, Wyd. PWN, 1983.
   - Jurlewicz T., Skoczylas Z., *Algebra liniowa 2. Definicje, twierdzenia, wzory*, Oficyna Wydawnicza GiS, 2002.
   - Rutkowski J., *Algebra liniowa w zadaniach*, Wyd. PWN, 2008.

2. **Uzupełniająca:**
   - Białynicki-Birula A., *Algebra liniowa z geometrią*, Wyd. PWN, 1979.
   - Mostowski A., Stark M., *Elementy algebry wyższej*, Wyd. PWN, 1970.

### Warunki zaliczenia:
- **Wykład:** Egzamin ustny poprzedzony testem pisemnym. Uzyskanie co najmniej 65% punktów z testu jest wymagane do pozytywnej oceny.
- **Ćwiczenia:** Dwa kolokwia pisemne. Zaliczenie ćwiczeń wymaga uzyskania co najmniej 50% punktów.
